apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      serviceAccountName: airflow
      containers:
      - name: airflow-scheduler
        image: apache/airflow:2.7.0
        command: ["airflow", "scheduler"]
        envFrom:
        - configMapRef:
            name: airflow-config
        volumeMounts:
        - name: dags-volume
          mountPath: /opt/airflow/dags
      volumes:
      # - name: dags-volume
      #   persistentVolumeClaim:
      #     claimName: airflow-dags-pvc 
      - name: dags-volume
        hostPath:
          path: /mnt/wsl/rancher-desktop/dags # Path on the Minikube host
          type: Directory # Ensure it points to a directory
