apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  namespace: airflow  # Ensure the namespace exists
data:
  # Database connection string
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow

  # Kubernetes executor namespace
  AIRFLOW__KUBERNETES_EXECUTOR__NAMESPACE: airflow

  # Delete worker pods after tasks are completed
  AIRFLOW__KUBERNETES_EXECUTOR__DELETE_WORKER_PODS: "True"

  # Worker container repository and tag
  AIRFLOW__KUBERNETES_EXECUTOR__WORKER_CONTAINER_REPOSITORY: apache/airflow
  AIRFLOW__KUBERNETES_EXECUTOR__WORKER_CONTAINER_TAG: 2.7.0

  # Persistent Volume Claim for DAGs
  AIRFLOW__KUBERNETES__DAGS_VOLUME_CLAIM: airflow-dags-pvc

  # Mount path for DAGs in Airflow
  AIRFLOW__KUBERNETES__DAGS_VOLUME_MOUNT_PATH: /opt/airflow/dags


  # Local logging configuration
  AIRFLOW__LOGGING__BASE_LOG_FOLDER: /opt/airflow/logs  # Replace with your desired log directory
  AIRFLOW__LOGGING__LOG_FORMAT: "[%(asctime)s] {%(filename)s:%(lineno)d} %(levelname)s - %(message)s"
 
  # Logging settings 
  AIRFLOW__CORE__REMOTE_LOGGING: "False"
  AIRFLOW__CORE__LOGGING_LEVEL: "INFO"