apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags-pv
  namespace: airflow
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOncePod 
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/wsl/rancher-desktop/airflow # Ensure this path exists on the host machine
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags-pvc
  namespace: airflow
spec:
  accessModes:
  - ReadWriteOncePod 
  resources:
    requests:
      storage: 1Gi
